# Generated by Django 2.2.1 on 2019-07-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='pricePerTablet',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='brandName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expireDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(default='', max_length=100),
        ),
    ]
