# Generated by Django 2.2.1 on 2019-07-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0003_auto_20190723_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
